Zane dev plugins
SynBioHub/synbiohub pull request #1508
Opened 2022-08-09 17:10 UTC by zane-perry

Added plugin endpoints to old backend

2022-08-09 17:18 UTC, JMante1 requested changes
It looks good. Just could you make sure the error messages are a little more informative. Adding more information as to what error and what plugin etc was called (just in case people think they are calling something else). So in general say what was sent and give a list of options that would work. Or a place to find those options (e.g. run get request to get a list of available plutins)

2022-08-09 17:18 UTC, JMante1 commented on lib/plugins/pluginEndpoints
> +        default: res.status(400).send('Error with request');
I think this could be clearer: e.g. this plugin type is not known, try evaluate, status, run, or call instead

2022-08-09 17:18 UTC, JMante1 commented on lib/plugins/pluginEndpoints
> +        return res.status(404).send('Plugin not found');
be clearer: the url called does not correspond to a plugin

2022-08-09 17:18 UTC, JMante1 commented on lib/plugins/pluginEndpoints
> +            return res.status(400).send('The Plugin is not Responding');
The plugin [plugin name] status endpoint is not responding

2022-08-10 13:48 UTC, cjmyers approved these changes

2022-08-10 13:49 UTC, cjmyers commented
I approve the changes but the docker build failed.  I'm not sure why.  I've restarted it.  We will not be able to merge until the build and tests all complete successfully.

2022-08-24 17:59 UTC, JMante1 approved these changes

2022-08-24 17:59 UTC, merged